from .mg import MGCrawler
from .timeslive import TimesLiveCrawler
from .citizen import CitizenCrawler
from .dailysun import DailysunCrawler
from .news24 import News24Crawler
from .iol import IOLCrawler
from .namibian import NamibianCrawler
from .generic import GenericCrawler
from .newstools import NewstoolsCrawler, NewstoolsCrawlerNT
from .zambia import ZambiaDailyNationCrawler, LusakaTimesCrawler, ZambianWatchdogCrawler, ZambiaDailyMailCrawler, PostZambiaCrawler, TimesZambiaCrawler
from .nationke import NationKECrawler
from .standardmedia import StandardMediaCrawler
from .thestarke import TheStarKECrawler
from .theeastafricanke import TheEastAfricanKECrawler
from .dailynewstz import DailyNewsTZCrawler
from .dailynewszw import DailyNewsZWCrawler
from .thecitizentz import TheCitizenTZCrawler
from .newsdayzw import NewsDayZWCrawler
from .dwcom import DWCrawler
from .chroniclezw import ChronicleZWCrawler
from .bbc import BBCCrawler
from .howwemadeitinafrica import HowWeMadeItInAfricaCrawler
from .savca import SAVCACrawler
from .rhodesunimathewblog import RhodesUniMathewBlogCrawler
from .worldstage import WorldStageCrawler
from .classicfm import ClassicFMCrawler
from .afp import AFPCrawler
from .naijanews import NaijaNewsCrawler
from .dailytrustnp import DailyTrustNPCrawler
from .newteleonline import NewTeleOnlineCrawler
from .thepoint import ThePointCrawler
from .dailytimes import DailyTimesCrawler
from .thenation import TheNationCrawler
from .mediamaxnet import MediaMaxNetCrawler
from .leadership import LeadershipCrawler
from .theinterview import TheInterviewCrawler
from .rsaparliament import RSAParliamentCrawler
from .guardian import GuardianCrawler
from .nationaldailyng import NationalDailyNgCrawler
from .nta import NTACrawler
from .acdivoca import ACDIVOCACrawler
from .thisdaylive import ThisDayLiveCrawler
from .channelafrica import ChannelAfricaCrawler
from .nan import NANCrawler
from .nigeriatoday import NigeriaTodayCrawler
from .businessdayonline import BusinessDayOnlineCrawler
from .standardmediaktnnews import StandardMediaKTNCrawler
from .globaltimescn import GlobalTimesCN
from .nationalmirror import NationalMirrorCrawler