"""taxonomies

Revision ID: 1a1c0f92befd
Revises: 44ec193d1661
Create Date: 2015-11-16 16:10:07.318965

"""

# revision identifiers, used by Alembic.
revision = '1a1c0f92befd'
down_revision = '44ec193d1661'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_taxonomies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_taxonomies_doc_id'), 'document_taxonomies', ['doc_id'], unique=False)
    op.create_index(op.f('ix_document_taxonomies_label'), 'document_taxonomies', ['label'], unique=False)
    op.create_index(op.f('ix_document_taxonomies_score'), 'document_taxonomies', ['score'], unique=False)
    op.drop_index('documents_text_ft_ix', table_name='documents')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('documents_text_ft_ix', 'documents', ['text'], unique=False)
    op.drop_index(op.f('ix_document_taxonomies_score'), table_name='document_taxonomies')
    op.drop_index(op.f('ix_document_taxonomies_label'), table_name='document_taxonomies')
    op.drop_index(op.f('ix_document_taxonomies_doc_id'), table_name='document_taxonomies')
    op.drop_table('document_taxonomies')
    ### end Alembic commands ###
