"""adjust user models to match flask-security

Revision ID: 213cdaf404ca
Revises: 2a3bbd3d21d
Create Date: 2015-03-25 11:57:14.612776

"""

# revision identifiers, used by Alembic.
revision = '213cdaf404ca'
down_revision = '2a3bbd3d21d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users CHANGE encrypted_password password VARCHAR(100) DEFAULT NULL")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users CHANGE password encrypted_password VARCHAR(100) DEFAULT NULL")
    ### end Alembic commands ###
