"""topic_analysis_nature_can_be_null

Revision ID: 22cca3f625d6
Revises: 4332e26568de
Create Date: 2015-04-23 11:25:19.520410

"""

# revision identifiers, used by Alembic.
revision = '22cca3f625d6'
down_revision = '4332e26568de'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'analysis_nature_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'1'"))
    op.execute("update topics set analysis_nature_id = null where analysis_nature_id = 1")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("update topics set analysis_nature_id = 1 where analysis_nature_id is null")
    op.alter_column('topics', 'analysis_nature_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'1'"))
    ### end Alembic commands ###
