"""tags

Revision ID: 3421025b5e5e
Revises: 3a36ba91e12c
Create Date: 2015-08-11 12:33:52.189782

"""

# revision identifiers, used by Alembic.
revision = '3421025b5e5e'
down_revision = '3a36ba91e12c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_tags_doc_id'), 'document_tags', ['doc_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_tags_doc_id'), table_name='document_tags')
    op.drop_table('document_tags')
    ### end Alembic commands ###
