"""remove legacy analysis_nature links

Revision ID: 41b4133d687e
Revises: 13781c95ccab
Create Date: 2016-03-15 13:16:36.363454

"""

# revision identifiers, used by Alembic.
revision = '41b4133d687e'
down_revision = '13781c95ccab'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'issues_ibfk_1', 'issues', type_='foreignkey')
    op.drop_column('issues', 'analysis_nature_id')
    op.drop_constraint(u'source_roles_ibfk_1', 'source_roles', type_='foreignkey')
    op.drop_column('source_roles', 'analysis_nature_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_roles', sa.Column('analysis_nature_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'source_roles_ibfk_1', 'source_roles', 'analysis_natures', ['analysis_nature_id'], ['id'])
    op.add_column('issues', sa.Column('analysis_nature_id', mysql.INTEGER(display_width=11), server_default=sa.text(u"'1'"), autoincrement=False, nullable=True))
    op.create_foreign_key(u'issues_ibfk_1', 'issues', 'analysis_natures', ['analysis_nature_id'], ['id'])
    ### end Alembic commands ###
