"""issue_analysis_nature_can_be_null

Revision ID: 4332e26568de
Revises: 4437cb6ea605
Create Date: 2015-04-23 11:08:04.988846

"""

# revision identifiers, used by Alembic.
revision = '4332e26568de'
down_revision = '4437cb6ea605'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'analysis_nature_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'1'"))
    op.execute("update issues set analysis_nature_id = null")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'analysis_nature_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'1'"))
    op.execute("update issues set analysis_nature_id = 1")
    ### end Alembic commands ###
