"""analysis nature topics

Revision ID: 44ec193d1661
Revises: 57f1d2b5c2b1
Create Date: 2015-08-13 13:07:26.025968

"""

# revision identifiers, used by Alembic.
revision = '44ec193d1661'
down_revision = '57f1d2b5c2b1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_nature_topics',
    sa.Column('analysis_nature_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_nature_id'], ['analysis_natures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE')
    )
    ### end Alembic commands ###

    # topics with an analysis nature
    op.execute("INSERT INTO analysis_nature_topics (analysis_nature_id, topic_id)" +
               " SELECT analysis_nature_id, id from topics where analysis_nature_id is not null")

    # topics for all analysis natures
    from dexter.models import AnalysisNature
    for nature in AnalysisNature.all():
        op.execute("INSERT INTO analysis_nature_topics (analysis_nature_id, topic_id)" +
                   " SELECT %d, id from topics where analysis_nature_id is null" % nature.id)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_nature_topics')
    ### end Alembic commands ###
