"""FDI edits v1.2

Revision ID: 455e2ffe5c2f
Revises: 57b0a21da161
Create Date: 2016-11-08 10:09:09.768252

"""

# revision identifiers, used by Alembic.
revision = '455e2ffe5c2f'
down_revision = '57b0a21da161'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investments', 'value',
                    type_=mysql.FLOAT(display_width=11),
                    )
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=True)
    op.create_table('involvements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_involvements_name'), 'involvements', ['name'], unique=True)
    op.create_table('value_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_value_units_name'), 'value_units', ['name'], unique=True)
    op.add_column(u'investments', sa.Column('fdi_notes', sa.String(length=1024), nullable=True))
    op.add_column(u'investments', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.add_column(u'investments', sa.Column('involvement_id', sa.Integer(), nullable=True))
    op.add_column(u'investments', sa.Column('value_unit_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_investments_industry_id'), 'investments', ['industry_id'], unique=False)
    op.create_index(op.f('ix_investments_involvement_id'), 'investments', ['involvement_id'], unique=False)
    op.create_index(op.f('ix_investments_value_unit_id'), 'investments', ['value_unit_id'], unique=False)
    op.create_foreign_key(None, 'investments', 'industries', ['industry_id'], ['id'])
    op.create_foreign_key(None, 'investments', 'involvements', ['involvement_id'], ['id'])
    op.create_foreign_key(None, 'investments', 'value_units', ['value_unit_id'], ['id'])
    op.drop_column(u'investments', 'government')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investments', 'value',
                    type_=mysql.INTEGER(display_width=11),
                    )
    op.add_column(u'investments', sa.Column('government', sa.String(length=1024), nullable=True))
    op.drop_constraint(u'investments_ibfk_8', 'investments', type_='foreignkey')
    op.drop_constraint(u'investments_ibfk_9', 'investments', type_='foreignkey')
    op.drop_constraint(u'investments_ibfk_10', 'investments', type_='foreignkey')
    op.drop_index(op.f('ix_investments_value_unit_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_involvement_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_industry_id'), table_name='investments')
    op.drop_column(u'investments', 'value_unit_id')
    op.drop_column(u'investments', 'involvement_id')
    op.drop_column(u'investments', 'industry_id')
    op.drop_column(u'investments', 'fdi_notes')
    op.drop_index(op.f('ix_value_units_name'), table_name='value_units')
    op.drop_table('value_units')
    op.drop_index(op.f('ix_involvements_name'), table_name='involvements')
    op.drop_table('involvements')
    op.drop_index(op.f('ix_industries_name'), table_name='industries')
    op.drop_table('industries')
    ### end Alembic commands ###
